server:
  port: 8083
spring:  
  cloud:
    gateway:
      routes:
        - id: moviesRoute
          uri: lb://MOVIE
          predicates:
           - Path=/movies/**
        - id: catalogRoute
          uri: lb://CATALOG
          predicates:
           - Path=/catalog/**
